#!/usr/bin/env python

import argparse
import json
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('cmd')
    args = parser.parse_args()

    for line in sys.stdin:
        if line.strip() == '':
            continue
        js = json.loads(line)
        out = eval(args.cmd, {'j': js})
        json.dump(out, sys.stdout)
        sys.stdout.write('\n')


if __name__ == '__main__':
    main()
