name: test
on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4 
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install .
      - run: pip install hacking
      - run: flake8
      - run: pytest --cov=jqp
      - run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
